language: android
script: "./gradlew build"
android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-23.0.2
    # The SDK version used to compile your project
    - android-23
    # Additional components
    #- extra-android-m2repository
